site_name: Azure DevOps Agent Operator
site_description: Kubernetes operator for elastically-scalable Azure DevOps self-hosted agents
repo_url: https://github.com/amaanx86/azure-devops-agent-operator
repo_name: GitHub
docs_dir: docs

extra_css:
  - assets/stylesheets/custom.css

nav:
  - Home: index.md
  - Setup: setup.md
  - Authentication: authentication.md
  - Usage: usage.md
  - Production: production.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: light
    primary: blue
    accent: blue
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
