# This rule is not used by the project azure-devops-agent-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to agents.amaanx86.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: azure-devops-agent-operator
    app.kubernetes.io/managed-by: kustomize
  name: agentpool-viewer-role
rules:
- apiGroups:
  - agents.amaanx86.github.io
  resources:
  - agentpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.amaanx86.github.io
  resources:
  - agentpools/status
  verbs:
  - get
